site_name: JSAC2024 Mihari Workshop

theme:
  name: material
  # ref. https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#automatic-light-dark-mode
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Index: index.md
  - Introduction: introduction.md
  - Setup: setup.md
  - Architecture: architecture.md
  - Rule: rule.md
  - Vs. ProjectDiscovery: vs_project_discovery.md
  - Operation: operation.md
  - Exercises:
      - Subdomain Enumeration: exercises/subdomain_enumeration.md
      - Honeypot: exercises/honeypot.md
      - MoqHao: exercises/moqhao.md
      - Nuclei: exercises/nuclei.md

plugins:
  search:

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.magiclink
  - mdx_truly_sane_lists:
      nested_indent: 2
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
